---
title: "code_snippets"
author: "Dominique Paul"
date: "6/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Function for DE old

```{r function for DE old, results='asis', eval=FALSE}

run_DE_analysis_old <- function(group1, group2){
  
  sce_filtered <- sce_filtered_backup
  
  sce_filtered <- sce_filtered[, sce_filtered$group %in% c(group1, group2)]
    
  colData(sce_filtered)$selected_group <- FALSE
  colData(sce_filtered)[sce_filtered$group == group1, "selected_group"] <- TRUE
  


  # Show frequency table
  print(kable(table(colLabels(sce_filtered), sce_filtered$selected_group)))
  cat("\n")
  
  print(plotTSNE(sce_filtered, colour_by="selected_group", text_by="label") +
      ggtitle(paste0("t-SNE plot with ", group1, " as selected group")))
  
  sce_filtered$label <- as.character(colLabels(sce_filtered))
  
  summed <- aggregateAcrossCells(sce_filtered, 
                                 id=colData(sce_filtered)[,c("label")])
  
  summed <- sumCountsAcrossCells(sce_filtered,
                                 ids=DataFrame(selected_group=sce_filtered$selected_group, label=sce_filtered$label, Sample=sce_filtered$Sample))
  
  de_results <- pseudoBulkDGE(summed,
                              label=summed$label,
                              design=~Sample + selected_group,
                              coef="selected_groupTRUE",
                              condition=summed$selected_group)
  
  return(de_results)

}

# abc <- run_DE_analysis_old("control (group 1)","TGFB (group 2)")
# print(metadata(abc)$failed)
# abc <- run_DE_analysis_old("control (group 1)","TGFB+akg (group 3)")
# print(metadata(abc)$failed)
# abc <- run_DE_analysis_old("control (group 1)","akg (group 4)")
# print(metadata(abc)$failed)
# abc <- run_DE_analysis_old("TGFB (group 2)","TGFB+akg (group 3)")
# print(metadata(abc)$failed)
# abc <- run_DE_analysis_old("TGFB (group 2)","akg (group 4)")
# print(metadata(abc)$failed)
# abc <- run_DE_analysis_old("TGFB+akg (group 3)","akg (group 4)")
# print(metadata(abc)$failed)
# 


# unique(sce_filtered$group)
# metadata(abc)$failed
```




```{r Differential Expression, eval=FALSE}

run_DE_analysis <- function(annotations_name){
  sce_filtered$Patient <-  substr(colnames(sce_filtered), 1, 1)
  
  colData(sce_filtered)$akg_treated <- FALSE
  colData(sce_filtered)[colnames(sce_filtered) %like% "AKG", "akg_treated"] <- TRUE
  
  # kable output
  kable(table(colData(sce_filtered)[[annotations_name]], sce_filtered$akg_treated))
  
  # tsne visualisation
  plotTSNE(sce_filtered, colour_by="akg_treated", text_by=annotations_name) +
    ggtitle(paste0("t-SNE plot with ", annotations_name, " annotations \n(coloured by AKG treatment status)"))
  
  summed <- aggregateAcrossCells(sce_filtered, 
      id=colData(sce_filtered)[,c(annotations_name, "Sample")])
  
  de_results <- pseudoBulkDGE(summed,
                              label=colData(summed)[[annotations_name]],
                              design=~factor(Patient)+akg_treated,
                              coef="akg_treatedTRUE",
                              condition=summed$akg_treated)
  
  is_de <- decideTestsPerLabel(de_results, threshold=0.05)
    
  # test summary
  summarizeTestsPerLabel(is_de)
  
  
  for(i in names(de_results)){
    cat(paste0("\nResults for ", i, " cell type:\n"))
    cur_results <- de_results[[i]]
    
    # print results by category
    print(cur_results[order(cur_results$PValue)[1:10],])
  }
}

model.matrix(~group + selected_group, summed$samples)
```
