---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

```{r, include=FALSE}
library(magrittr)

all_files_analysis <- list.files(here::here("docs"))
all_files_output <- list.files(here::here("docs/output"))

mod_times <- data.frame(filename = c(all_files_analysis,all_files_output),
           date = c(file.info(here::here("docs", all_files_analysis))$mtime,file.info(here::here("docs/output",all_files_output))$mtime) %>% 
             as.Date(format = "%m/%d/%y"))

give_date <- function(filename, dataframe = mod_times){
  tmpout <- dataframe$date[dataframe$filename == filename]
  if (length(tmpout) == 0){
    tmpout <- "never"
  }
  paste0("  *<font size=\"1\">(Last modified: ",tmpout," )</font>*")
}
```

# iSEE App

Click here to open iSEE app: <a target="_blank" href="http://imlspenticton.uzh.ch:3839/iSEE/">http://imlspenticton.uzh.ch:3839/iSEE/</a>



# Fresh only  & Fresh v. Culture

1. [Comparison of data processed with the new protocol with skin control samples](P2_01_data_comparison.html) `r give_date("P2_data_comparison.html")`
1. [Cell cycle analysis](P2_02_Cell_Cycle.html) `r give_date("P2_data_comparison.html")`
1. Fresh only:
    1. [Fresh only subclustering](P2_03_Fresh_only_subclustering.html) `r give_date("P2_03_Fresh_only_subclustering.html")`
1. Fresh vs. Culture:
    1. [FvC: Annotations](P2_03_FvC_Annotations.html) `r give_date("P2_03_FvC_Annotations.html")`


### Downloads

1. <p>Fresh only marker genes: <a href="output/P2_Fresh_only.xlsx">Click to Download</a> `r give_date("P2_Fresh_only.xlsx")`</p>
1. <p>Fresh and culture marker genes: <a href="output/P2_Fresh_v_culture.xlsx">Click to Download</a> `r give_date("P2_Fresh_v_culture.xlsx")`</p>



# External data integration

1. [Data preparation](EDI_01_Loading_and_Preprocessing.html)  `r give_date("EDI_01_Loading_and_Preprocessing.html")`
1. [Normalisation and selection of HVGs](EDI_02_Normalisation_HVG_DimRed.html)  `r give_date("EDI_02_Normalisation_HVG_DimRed.html")`
1. [Batch correction and clustering](EDI_03_Batch_correction.html)  `r give_date("EDI_03_Batch_correction.html")`
1. [Cell cycle analysis](EDI_04_Cell_Cycle.html)  `r give_date("EDI_04_Cell_Cycle.html")`
1. [Cell annotation](EDI_05_Annotation.html)  `r give_date("EDI_05_Annotation.html")`
1. [Marker gene analysis](EDI_06_marker_genes.html)  `r give_date("EDI_06_marker_genes.html")`
1. [Differential abundance analysis](EDI_07_DA.html)  `r give_date("EDI_07_DA.html")`
1. [Subclustering of selected cell types](EDI_08_Subclustering.html)  `r give_date("EDI_08_Subclustering.html")`

## Downloads

1. <p>EDI: Marker genes: <a href="output/EDI_marker_results_hvg_genes.xlsx" download>Click to download</a> `r give_date("EDI_marker_results_hvg_genes.xlsx")` </p>
1. <p>EDI subclustering: Marker genes: <a href="output/EDI_subclustering_markers_genes.xlsx" download>Click to download</a> `r give_date("EDI_subclustering_markers_genes.xlsx")` </p>

# Additional analysis

1. [Heat shock proteins](HSP_analysis.html)  `r give_date("HSP_analysis.html")`



